---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: httpbin-common
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./deploy/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: httpbin
  validation: client

