---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: httpbin-frontend
  namespace: flux-system
spec:
  dependsOn:
  - name: httpbin-common
  interval: 1m0s
  path: ./deploy/frontend
  prune: false
  sourceRef:
    kind: GitRepository
    name: httpbin
  timeout: 2m0s
  validation: client

